- project:
    check:
      jobs:
        - horizon-openstack-tox-py27dj110
        - horizon-openstack-tox-py27dj19
        - horizon-openstack-tox-py27dj18
    gate:
      jobs:
        - horizon-openstack-tox-py27dj110
        - horizon-openstack-tox-py27dj19
        - horizon-openstack-tox-py27dj18
